[package]
name = "anima-weave-dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
serde.workspace = true
thiserror.workspace = true
anima-weave-core = { path = "../core" }
