spring:
  application:
    name: animaweave
  profiles:
    active: dev
  
  # Web服务配置
  server:
    port: 8080
    servlet:
      context-path: /api/animaweave
  
  # Jackson JSON配置
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: SNAKE_CASE

  # 缓存配置
  cache:
    type: simple
    cache-names:
      - graph-cache
      - vessel-cache
      - execution-cache

# AnimaWeave特定配置
animaweave:
  # 执行引擎配置
  engine:
    max-concurrent-graphs: 10
    execution-timeout-seconds: 30
    enable-debug-mode: true
    
  # DSL解析器配置
  parser:
    max-nodes-per-graph: 1000
    max-connections-per-node: 100
    enable-validation: true
    
  # Vessel系统配置
  vessels:
    # 基础数学vessels
    math:
      enabled: true
      precision: double
    
    # 控制流vessels
    control:
      enabled: true
      async-execution: true
      
    # 数据处理vessels
    data:
      enabled: true
      buffer-size: 1024

# Anima文件生成器配置
anima:
  generator:
    output-directory: "sanctums"
    generated-file-suffix: ""
    file-extension: ".anima"
    overwrite-existing: true
    validate-after-generation: true
    verbose-logging: false

# 日志配置
logging:
  level:
    SeeleFelix.AnimaWeave: DEBUG
    org.springframework: INFO
    org.antlr: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator配置（用于监控）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
      
animaweave:
  engine:
    enable-debug-mode: true
  vessels:
    math:
      precision: double

logging:
  level:
    SeeleFelix.AnimaWeave: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
      
animaweave:
  engine:
    enable-debug-mode: false
    max-concurrent-graphs: 50
    execution-timeout-seconds: 60

logging:
  level:
    SeeleFelix.AnimaWeave: INFO
    root: WARN 